---
- hosts: database
  become: true
  gather_facts: false
  tasks:
    - name: install mysql-server
      apt:
        name: mysql-server
        state: present 
        update_cache: yes

    - name: ensure mysql-server started
      service:
        name: mysql 
        state: started
        enabled: yes

    - name: install tools
      apt:
        name: "{{ item }}"
        state: present 
        update_cache: yes
      loop: 
        - python3-mysqldb
    
    - name: create demo database  
      mysql_db:
        name: demo 
        state: present 

    - name: create demo user
      mysql_user:
        name: demo 
        password: demo 
        priv: demo.*ALL 
        host: '%'
        state: present 
    
    # - name: ensure mysql is listening on all ports 
    #   lineinfile: 
    #     dest: /etc/mysql/my.cnf 
    #     regexp: ^bind-address
    #     line: "bind-address = 0.0.0.0"
    #   notify: restart mysql-server

  handlers:
    - name: restart mysql-server
      service: 
        name: mysql
        state: restarted

  