---
- hosts: loadbalancer
  gather_facts: false
  become: true
  tasks:
    - service: 
        name: nginx
        state: stopped
    - wait_for: 
        port: 80
        status: drained

- hosts: webserver
  gather_facts: false
  become: true
  tasks:
    - service: 
        name: apache2
        state: stopped
    - wait_for: 
        port: 80
        status: drained

- hosts: database
  gather_facts: false
  become: true
  tasks:
    - service: 
        name: mysql
        state: restarted
    - wait_for: 
        port: 3306
        status: started
      
- hosts: loadbalancer
  gather_facts: false
  become: true
  tasks:
    - service: 
        name: nginx
        state: started
    - wait_for: 
        port: 80

- hosts: webserver
  gather_facts: false
  become: true
  tasks:
    - service: 
        name: apache2
        state: started
    - wait_for: 
        port: 80



