---
- hosts: webserver
  become: true
  gather_facts: false
  roles:
    - apache2
    - demo_app
  # vars:
  #   packages:
  #       - apache2
  #       - libapache2-mod-wsgi-py3
  #       - python3-pip
  #       - python3-virtualenv
  # tasks:
      # loop_control:
      #   index_var: index
      #   # loop_var: package
      #   label: "{{ index }}"











