---
- hosts: database
  become: true
  gather_facts: false
  tasks:
    - name: install mysql-server
      apt:
        name: mysql-server
        state: present 
        update_cache: yes

    - name: ensure mysql-server started
      service:
        name: mysql 
        state: started
        enabled: yes