---
- hosts: loadbalancer
  gather_facts: false
  become: true
  tasks:
    - service: 
        name: nginx
        state: stopped

- hosts: webserver
  gather_facts: false
  become: true
  tasks:
    - service: 
        name: apache2
        state: stopped

- hosts: database
  gather_facts: false
  become: true
  tasks:
    - service: 
        name: mysql
        state: stopped
      
- hosts: loadbalancer
  gather_facts: false
  become: true
  tasks:
    - service: 
        name: nginx
        state: started

- hosts: webserver
  gather_facts: false
  become: true
  tasks:
    - service: 
        name: apache2
        state: started

- hosts: database
  gather_facts: false
  become: true
  tasks:
    - service: 
        name: mysql
        state: started


